version: "3.9"

networks:
  deportistas_net:

volumes:
  postgres_data:

services:

  test-db:
    container_name: 'test-db'
    image: postgres
    env_file:
      - ./envs/.env.test
    environment:
      PGDATA: /data/postgres
    volumes:
       - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always

  deportistas-db:
    container_name: 'deportistas-db'
    image: postgres
    env_file:
      - ./envs/.env.db.local
    environment:
      PGDATA: /data/postgres
    volumes:
       - postgres_data:/var/lib/postgresql/data/
    networks:
      - deportistas_net
    ports:
      - 5432:5432
    restart: always

  usuarios-api:
    container_name: usuarios-api
    build:
      context: ./
      dockerfile: usuarios.Dockerfile
    env_file:
      - ./envs/.env.db.local
      - ./envs/.env.autenticador.local
      - ./envs/.env.usuarios.local
    networks:
      - deportistas_net
    ports:
      - 3011:3011
    restart: always

  perfiles-api:
    container_name: 'perfiles-api'
    build:
      context: ./
      dockerfile: perfiles.Dockerfile
    env_file:
      - ./envs/.env.db.local
      - ./envs/.env.autenticador.local
      - ./envs/.env.perfiles.local
    networks:
      - deportistas_net
    ports:
      - 3021:3021
    restart: always

  planes-api:
    container_name: 'planes-api'
    build:
      context: ./
      dockerfile: planes.Dockerfile
    env_file:
      - ./envs/.env.db.local
      - ./envs/.env.autenticador.local
      - ./envs/.env.planes.local
    networks:
      - deportistas_net
    ports:
      - 3030:3030
    restart: always

  # monitor-api:
  #   container_name: 'monitor-api'
  #   volumes:
  #     - ./src/monitor/outputs:/src/monitor/outputs
  #   build:
  #     context: ./
  #     dockerfile: monitor.Dockerfile
  #   env_file:
  #     - ./src/monitor/.env.monitor.local
  #   networks:
  #     - deportistas_net
  #   ports:
  #     - 3200:3200
  #   restart: always

  autenticador-api:
    container_name: 'autenticador-api'
    build:
      context: ./
      dockerfile: autenticador.Dockerfile
    env_file:
      - ./envs/.env.autenticador.local
    networks:
      - deportistas_net
    ports:
      - 3000:3000
    restart: always

  sesiones-api:
    container_name: 'sesiones-api'
    build:
      context: ./
      dockerfile: sesiones.Dockerfile
    env_file:
      - ./envs/.env.db.local
      - ./envs/.env.autenticador.local
      - ./envs/.env.sesiones.local
    networks:
      - deportistas_net
    ports:
      - 3070:3070
    restart: always

  eventos-api:
    container_name: 'eventos-api'
    build:
      context: ./
      dockerfile: eventos.Dockerfile
    env_file:
      - ./envs/.env.db.local
      - ./envs/.env.autenticador.local
      - ./envs/.env.eventos.local
    networks:
      - deportistas_net
    ports:
      - 3080:3080
    restart: always

  productos-api:
    container_name: 'productos-api'
    build:
      context: ./
      dockerfile: productos.Dockerfile
    env_file:
      - ./envs/.env.db.local
      - ./envs/.env.autenticador.local
      - ./envs/.env.productos.local
    networks:
      - deportistas_net
    ports:
      - 3090:3090
    restart: always

  indicadores-api:
    container_name: 'indicadores-api'
    build:
      context: ./
      dockerfile: indicadores.Dockerfile
    env_file:
      - ./envs/.env.db.local
      - ./envs/.env.autenticador.local
      - ./envs/.env.indicadores.local
    networks:
      - deportistas_net
    ports:
      - 3060:3060
    restart: always

  notificaciones-api:
    container_name: 'notificaciones-api'
    build:
      context: ./
      dockerfile: notificaciones.Dockerfile
    env_file:
      - ./envs/.env.db.local
      - ./envs/.env.notificaciones.local
    networks:
      - deportistas_net
    ports:
      - 3050:3050
    restart: always
