version: "3.9"

networks:
  deportistas_net:

volumes:
  postgres_data:

services:
  deportistas-db:
    container_name: 'deportistas-db'
    image: postgres
    env_file:
      - ./envs/.env.db.local
    environment:
      PGDATA: /data/postgres
    volumes:
       - postgres_data:/var/lib/postgresql/data/
    networks:
      - deportistas_net
    ports:
      - 5432:5432
    restart: always
  
  usuarios-api:
    container_name: usuarios-api
    depends_on:
      - deportistas-db
    build:
      context: ./
      dockerfile: usuarios.Dockerfile
    env_file:
      - ./envs/.env.db.local
      - ./envs/.env.jwt.local
      - ./envs/.env.usuarios.local
    networks:
      - deportistas_net
    ports:
      - 3011:3011
    restart: always
  
  perfiles-api:
    container_name: 'perfiles-api'
    depends_on:
      - deportistas-db
    build:
      context: ./
      dockerfile: perfiles.Dockerfile
    env_file:
      - ./envs/.env.db.local
      - ./envs/.env.jwt.local
      - ./envs/.env.perfiles.local
    networks:
      - deportistas_net
    ports:
      - 3021:3021
    restart: always

  monitor-api:
    container_name: 'monitor-api'
    depends_on:
      - usuarios-api
      - perfiles-api
    volumes:
      - ./src/monitor/outputs:/src/monitor/outputs
    build:
      context: ./
      dockerfile: monitor.Dockerfile
    env_file:
      - ./src/monitor/.env.monitor.local
    networks:
      - deportistas_net
    ports:
      - 3200:3200
    restart: always

