apiVersion: apps/v1
kind: Deployment
metadata:
  name: autenticador
  labels:
    app: autenticador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autenticador
  template:
    metadata:
      labels:
        app: autenticador
    spec:
      containers:
        - name: autenticador
          image: us-central1-docker.pkg.dev/proyecto-final-416123/proyecto-final/jwt-api:1.0.0
          env:
            - name: "JWT_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  name: authsecrets 
                  key: jwtsecretkey
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets 
                  key: pgsqluser
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets 
                  key: pgsqlpassword
            - name: "DB_HOST"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets 
                  key: pgsqlhost
            - name: "DB_PORT"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets 
                  key: pgsqlport
            - name: "DB_NAME"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets 
                  key: pgsqlname
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: autenticador-backend-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 3000
    type: HTTP
    requestPath: /healthcheck
---

apiVersion: v1
kind: Service
metadata:
  name: autenticador-service
  annotations:
    cloud.google.com/backend-config: '{"default": "autenticador-backend-config"}'
spec:
  type: NodePort
  selector:
    app: autenticador
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000