apiVersion: apps/v1
kind: Deployment
metadata:
  name: planes
  labels:
    app: planes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planes
  template:
    metadata:
      labels:
        app: planes
    spec:
      containers:
        - name: planes
          image: us-central1-docker.pkg.dev/proyecto-final-416123/misw450x-registry/planes-api:latest
          env:
            - name: "JWT_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  name: authsecrets
                  key: jwtsecretkey
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: pgsqluser
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: pgsqlpassword
            - name: "DB_HOST"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: pgsqlhost
            - name: "DB_PORT"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: pgsqlport
            - name: "DB_NAME"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: pgsqlname
          ports:
            - containerPort: 3030
          imagePullPolicy: Always
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: planes-backend-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 3030
    type: HTTP
    requestPath: /health
---
apiVersion: v1
kind: Service
metadata:
  name: planes-service
  annotations:
    cloud.google.com/backend-config: '{"default": "planes-backend-config"}'
spec:
  type: NodePort
  selector:
    app: planes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030
      nodePort: 30030
