apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  labels:
    app: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: monitor
          image: us-central1-docker.pkg.dev/misw4301-g19/uniandes-misw-4301-registry/monitor-api:1.0.0
          env:
            - name: "JWT_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  name: authsecretes 
                  key: jwtsecretkey
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets 
                  key: pgsqluser
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets 
                  key: pgsqlpassword
            - name: "DB_HOST"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets 
                  key: pgsqlhost
            - name: "DB_PORT"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets 
                  key: pgsqlport
            - name: "DB_NAME"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets 
                  key: pgsqlname
          ports:
            - containerPort: 3010
          imagePullPolicy: Always
---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: monitor-backend-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 3010
    type: HTTP
    requestPath: /healthcheck
---

apiVersion: v1
kind: Service
metadata:
  name: monitor-service
  annotations:
    cloud.google.com/backend-config: '{"default": "monitor-backend-config"}'
spec:
  type: NodePort
  selector:
    app: monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3010
      nodePort: 30010
---
