apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventos
  labels:
    app: eventos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventos
  template:
    metadata:
      labels:
        app: eventos
    spec:
      containers:
        - name: eventos
          image: us-central1-docker.pkg.dev/proyecto-final-416123/misw450x-registry/eventos-api:latest
          env:
            - name: "JWT_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  name: authsecrets
                  key: jwtsecretkey  
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: pgsqluser
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: pgsqlpassword
            - name: "DB_HOST"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: pgsqlhost
            - name: "DB_PORT"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: pgsqlport
            - name: "DB_NAME"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: pgsqlname
          ports:
            - containerPort: 3011
          imagePullPolicy: Always
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: eventos-backend-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 3011
    type: HTTP
    requestPath: /health
---
apiVersion: v1
kind: Service
metadata:
  name: eventos-service
  annotations:
    cloud.google.com/backend-config: '{"default": "eventos-backend-config"}'
spec:
  type: NodePort
  selector:
    app: eventos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3080
      nodePort: 30080
