apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios
  labels:
    app: usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: tasks-key
      containers:
        - name: usuarios
          image: us-central1-docker.pkg.dev/proyecto-final-416123/misw450x-registry/usuarios-api:latest
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: "JWT_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  name: authsecrets
                  key: jwtsecretkey
            - name: "AUTH_BASE_URL"
              value: http://autenticador-service/auth
            - name: "INTEGRATION_EVENT_URL"
              value: http://perfiles-service/demografico/init
            - name: "LOCATION_ID"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: locationid
            - name: "PROJECT_ID"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: projectid
            - name: "QUEUE_ID"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: queueusuariosid
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: pgsqluser
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: pgsqlpassword
            - name: "DB_HOST"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: pgsqlhost
            - name: "DB_PORT"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: pgsqlport
            - name: "DB_NAME"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets
                  key: pgsqlname

          ports:
            - containerPort: 3011
          imagePullPolicy: Always
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: usuarios
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: usuarios
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: usuarios-backend-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 3011
    type: HTTP
    requestPath: /health
---
apiVersion: v1
kind: Service
metadata:
  name: usuarios-service
  annotations:
    cloud.google.com/backend-config: '{"default": "usuarios-backend-config"}'
spec:
  type: NodePort
  selector:
    app: usuarios
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3011
      nodePort: 30011
