
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfiles
  labels:
    app: perfiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perfiles
  template:
    metadata:
      labels:
        app: perfiles
    spec:
      containers:
        - name: perfiles
          image: us-central1-docker.pkg.dev/misw4301-g19/uniandes-misw-4301-registry/perfiles-api:1.0.0
          env:
            - name: "JWT_SECRET_KEY"
              valueFrom:
                secretKeyRef:
                  name: authsecretes 
                  key: jwtsecretkey
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets 
                  key: pgsqluser
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets 
                  key: pgsqlpassword
            - name: "DB_HOST"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets 
                  key: pgsqlhost
            - name: "DB_PORT"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets 
                  key: pgsqlport
            - name: "DB_NAME"
              valueFrom:
                secretKeyRef:
                  name: deportistasecrets 
                  key: pgsqlname
          ports:
            - containerPort: 3021
          imagePullPolicy: Always
---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: perfiles-backend-config
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 3021
    type: HTTP
    requestPath: /healthcheck
---

apiVersion: v1
kind: Service
metadata:
  name: perfiles-service
  annotations:
    cloud.google.com/backend-config: '{"default": "perfiles-backend-config"}'
spec:
  type: NodePort
  selector:
    app: perfiles
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3021
      nodePort: 30021
---
