apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress-k8
  labels:
    name: gateway-ingress-k8
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /usuarios
        backend:
          service:
            name: usuarios-service
            port: 
              number: 80
      - pathType: Prefix
        path: /perfiles
        backend:
          service:
            name: perfiles-service
            port: 
              number: 80
      - pathType: Prefix
        path: /jwt
        backend:
          service:
            name: autenticador-service
            port: 
              number: 80
      - pathType: Prefix
        path: /monitor
        backend:
          service:
            name: monitor-service
            port: 
              number: 80
